project:
  type: website
  output-dir: docs

website:
  description: "A blog built with Quarto"
  site-url: https://heinrichsophia.github.io/portfolio # Update this URL
  title: "portfolio"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Resume"
        href: resume.pdf
      - text: "Cover Letter"
        href: cover_letter.pdf
      - icon: github
        href: https://github.com/heinrichsophia/portfolio
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
